name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run pre-commit 
      run: |
        poetry run pre-commit run --all-files

    - name: Format with Black
      run: |
        make format

    - name: Run tests
      run: |
        make test

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{github.actor}}
        password: ${{secrets.MY_SECRET_KEY}}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{github.repository}}/python_calculator .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{github.repository}}/python_calculator